### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by RCXcrafter** [Axanthic-Game-Studios/Lands-of-Icaria#1]
- Important stuff
- [x] Portal for traveling to and from the dimension
- [ ] Ruins and dungeons
- [x] Proper loot for vases
- [ ] More uses for the ingots we have
- [x] Something against infinite vine growth
- [x] Early survival tools for getting started
- Less important stuff
- [ ] Redo ore generation
- [ ] Lore
- [x] Crops
- [x] Water
- [x] Dolomite decoration blocks
- [ ] Grapes
- [x] Brewing system with herbs
- [ ] Spells to craft with the brewing system
- [ ] Fuel for the grinder
- [ ] Glowing wisp like mob
- [x] Make forest hags plant saplings
- [ ] Shields
- [x] Advancements
- [ ] Light source blocks
- [ ] A recipe for the sharpened bone
- [ ] A use for molibos
- [ ] A use for sliver
- [ ] A use for bluridium
- [ ] A use for hyliastrum
- [ ] A use for abyssal essence
- [ ] A use for jasper
- [ ] A use for zircon
- [ ] A use for revenant femur
- [ ] A use for aeternae fur
- [x] A use for aeternae leather
- [ ] A use for snull cream

**Comment by RCXcrafter** [comment]
This is outdated now
